### ISSUE TITLE
Autoloading - Latest release (v3.0.0) is not PSR-4 compliant

### ISSUE THREAD

**Issue by lephleg** [moosend/phpwrapper#4]
Hello,

Is there an issue with autoloading the package on version v3.0.0?

I just upgraded the package on Laravel 5.7 and I keep getting the following error:

```
Class 'Swagger\\Client\\Api\\SubscribersApi' not found
```

I run `composer dump-autoload` and ensured the imports are correct, but it doesn't seem to load the class. The actual package files have been installed alright in my `vendors/moosend/phpwrapper` directory.

I suspect your package **is not psr-4 compliant**, so I would like instructions on how to autoload it correctly.

**Comment by lephleg** [comment]
The workaround is to autoload the package explicitly using `classmap` in your `composer.json`:

```
  "autoload": {
    "classmap": [
      "vendor/moosend/phpwrapper/lib"
    ],
```

**Comment by gentsp** [comment]
Hi Argyris,

We have made a release for this fix. You can find it in our _master_ branch or _v3.0.1_ tag.

You can also change the path to point to our _autoload_ file inside library.

Thanks
